// Code generated by 'yaegi extract github.com/magpierre/go_delta_sharing_client'. DO NOT EDIT.

package windows

import (
	"reflect"

	delta_sharing "github.com/magpierre/go_delta_sharing_client"
)

// DeltaSharingSymbols contains the symbols for the delta_sharing package
var DeltaSharingSymbols = map[string]map[string]reflect.Value{}

func init() {
	DeltaSharingSymbols["github.com/magpierre/go_delta_sharing_client/delta_sharing"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"LoadArrowTable":             reflect.ValueOf(delta_sharing.LoadArrowTable),
		"LoadAsArrowTable":           reflect.ValueOf(delta_sharing.LoadAsArrowTable),
		"NewSharingClient":           reflect.ValueOf(delta_sharing.NewSharingClient),
		"NewSharingClientFromString": reflect.ValueOf(delta_sharing.NewSharingClientFromString),

		// type definitions
		"CDFFile":        reflect.ValueOf((*delta_sharing.CDFFile)(nil)),
		"CdfOptions":     reflect.ValueOf((*delta_sharing.CdfOptions)(nil)),
		"DSErr":          reflect.ValueOf((*delta_sharing.DSErr)(nil)),
		"DataChangeFile": reflect.ValueOf((*delta_sharing.DataChangeFile)(nil)),
		"File":           reflect.ValueOf((*delta_sharing.File)(nil)),
		"RemoveFile":     reflect.ValueOf((*delta_sharing.RemoveFile)(nil)),
		"SharingClient":  reflect.ValueOf((*delta_sharing.SharingClient)(nil)),
		"Table":          reflect.ValueOf((*delta_sharing.Table)(nil)),
	}
}
